[package]
name = "equart"
version = "0.3.0"
authors = ["George Shuklin <george.shuklin@gmail.com>"]
edition = "2018"

[[bin]]
name = "equart"
path = "src/main.rs"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
sdl2 = {version="*"}
bytemuck = "*"

[dev-dependencies]
criterion = "*"
